sudo: required
dist: trusty

notifications:
  email: false

services:
  - docker

language: java

jdk:
  - openjdk7

env:
  matrix:
    - DOCKER_VERSION=17.12.1~ce DOCKER_CE=1

before_install:
  # check what version of docker is installed beforehand
  - dpkg -l | grep docker
  # install the version of docker in the DOCKER_VERSION env var
  - ./.travis.sh install_docker
  # uncomment to double-check that the version/config is correct
  # - ./.travis.sh dump_docker_config
  - docker version
  - docker info

script: mvn clean -Dsurefire.rerunFailingTestsCount=1 test

# To troubleshoot a failing build, you can uncomment this block to dump the
# docker logs in case they are needed for troubleshooting failures. We don't do
# this on every single build as the logs are verbose and noisy.
# after_script:
#   - sudo cat /var/log/upstart/docker.log

branches:
  only:
    - master
