sudo: required
dist: trusty

notifications:
  email: false

services:
  - docker

language: java

jdk:
  - openjdk7

before_install:
  # check what version of docker is installed beforehand
  - dpkg -l | grep docker
  # install the version of docker in the DOCKER_VERSION env var
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=17.12.1~ce-0~ubuntu
  - docker swarm init
  # uncomment to double-check that the version/config is correct
  # - ./.travis.sh dump_docker_config
  - docker version
  - docker info

script: mvn clean -Dsurefire.rerunFailingTestsCount=1 test

# To troubleshoot a failing build, you can uncomment this block to dump the
# docker logs in case they are needed for troubleshooting failures. We don't do
# this on every single build as the logs are verbose and noisy.
# after_script:
#   - sudo cat /var/log/upstart/docker.log

branches:
  only:
    - master
